### ISSUE TITLE
Vector connection was stopped in the upload log

### ISSUE THREAD

**Issue by e8tg001** [zinclabs/zincobserve#485] opened 2023-04-01 09:45 UTC
### Which ZincObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

[#484 ](https://github.com/zinclabs/zincobserve/issues/484) subsequent error for this problem,log upload is automatically interrupted

collector: Vector 

Vector print error logs :
2023-04-01T09:01:37.892876Z  WARN sink{component_kind="sink" component_id=zinc component_type=http component_name=zinc}:request{request_id=120}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: connection error: 你的主机中的软件中止了一个已建立的连接。 (os error 10053) internal_log_rate_limit=true

### Please provide the exception or error you saw

```true
repeated emergence
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
version:0.3.1
sha1sum:8ade56d4da0ac28981eb32e5fbe75a8214a68ba3
Linux centos72.9377 3.10.0-957.21.3.el7.x86_64   
8*CPU  
16G
```

**Comment by prabhatsharma** [comment] 2023-04-01 22:45
closing this as duplicate of #484 since the cause is same.

**Closed by prabhatsharma** 2023-04-01 22:45 UTC
